#include <assert.h>
#include <dlfcn.h>

#include "full.h"

meshlink_errno_t *full_meshlink_errno;
const char *(*full_meshlink_strerror)(meshlink_errno_t err) __attribute__((__warn_unused_result__));
meshlink_open_params_t *(*full_meshlink_open_params_init)(const char *confbase, const char *name, const char *appname, dev_class_t devclass) __attribute__((__warn_unused_result__));
void (*full_meshlink_open_params_free)(meshlink_open_params_t *params);
bool (*full_meshlink_open_params_set_netns)(meshlink_open_params_t *params, int netns) __attribute__((__warn_unused_result__));
bool (*full_meshlink_open_params_set_storage_key)(meshlink_open_params_t *params, const void *key, size_t keylen) __attribute__((__warn_unused_result__));
bool (*full_meshlink_open_params_set_storage_policy)(meshlink_open_params_t *params, meshlink_storage_policy_t policy) __attribute__((__warn_unused_result__));
bool (*full_meshlink_open_params_set_lock_filename)(meshlink_open_params_t *params, const char *filename) __attribute__((__warn_unused_result__));
struct meshlink_handle *(*full_meshlink_open_ex)(const meshlink_open_params_t *params) __attribute__((__warn_unused_result__));
struct meshlink_handle *(*full_meshlink_open)(const char *confbase, const char *name, const char *appname, dev_class_t devclass) __attribute__((__warn_unused_result__));
struct meshlink_handle *(*full_meshlink_open_encrypted)(const char *confbase, const char *name, const char *appname, dev_class_t devclass, const void *key, size_t keylen) __attribute__((__warn_unused_result__));
struct meshlink_handle *(*full_meshlink_open_ephemeral)(const char *name, const char *appname, dev_class_t devclass) __attribute__((__warn_unused_result__));
struct meshlink_submesh *(*full_meshlink_submesh_open)(struct meshlink_handle *mesh, const char *submesh) __attribute__((__warn_unused_result__));
bool (*full_meshlink_start)(struct meshlink_handle *mesh) __attribute__((__warn_unused_result__));
void (*full_meshlink_stop)(struct meshlink_handle *mesh);
void (*full_meshlink_close)(struct meshlink_handle *mesh);
bool (*full_meshlink_destroy)(const char *confbase) __attribute__((__warn_unused_result__));
bool (*full_meshlink_destroy_ex)(const meshlink_open_params_t *params) __attribute__((__warn_unused_result__));
void (*full_meshlink_set_receive_cb)(struct meshlink_handle *mesh, meshlink_receive_cb_t cb);
void (*full_meshlink_set_connection_try_cb)(struct meshlink_handle *mesh, meshlink_connection_try_cb_t cb);
void (*full_meshlink_set_node_status_cb)(struct meshlink_handle *mesh, meshlink_node_status_cb_t cb);
void (*full_meshlink_set_node_pmtu_cb)(struct meshlink_handle *mesh, meshlink_node_pmtu_cb_t cb);
void (*full_meshlink_set_node_duplicate_cb)(struct meshlink_handle *mesh, meshlink_node_duplicate_cb_t cb);
void (*full_meshlink_set_log_cb)(struct meshlink_handle *mesh, meshlink_log_level_t level, meshlink_log_cb_t cb);
void (*full_meshlink_set_error_cb)(struct meshlink_handle *mesh, meshlink_error_cb_t cb);
void (*full_meshlink_set_blacklisted_cb)(struct meshlink_handle *mesh, meshlink_blacklisted_cb_t cb);
bool (*full_meshlink_send)(struct meshlink_handle *mesh, struct meshlink_node *destination, const void *data, size_t len) __attribute__((__warn_unused_result__));
ssize_t (*full_meshlink_get_pmtu)(struct meshlink_handle *mesh, struct meshlink_node *destination) __attribute__((__warn_unused_result__));
struct meshlink_node *(*full_meshlink_get_self)(struct meshlink_handle *mesh) __attribute__((__warn_unused_result__));
struct meshlink_node *(*full_meshlink_get_node)(struct meshlink_handle *mesh, const char *name) __attribute__((__warn_unused_result__));
struct meshlink_submesh *(*full_meshlink_get_submesh)(struct meshlink_handle *mesh, const char *name) __attribute__((__warn_unused_result__));
char *(*full_meshlink_get_fingerprint)(struct meshlink_handle *mesh, struct meshlink_node *node) __attribute__((__warn_unused_result__));
struct meshlink_node **(*full_meshlink_get_all_nodes)(struct meshlink_handle *mesh, struct meshlink_node **nodes, size_t *nmemb) __attribute__((__warn_unused_result__));
bool (*full_meshlink_sign)(struct meshlink_handle *mesh, const void *data, size_t len, void *signature, size_t *siglen) __attribute__((__warn_unused_result__));
struct meshlink_node **(*full_meshlink_get_all_nodes_by_dev_class)(struct meshlink_handle *mesh, dev_class_t devclass, struct meshlink_node **nodes, size_t *nmemb) __attribute__((__warn_unused_result__));
struct meshlink_node **(*full_meshlink_get_all_nodes_by_submesh)(struct meshlink_handle *mesh, struct meshlink_submesh *submesh, struct meshlink_node **nodes, size_t *nmemb) __attribute__((__warn_unused_result__));
struct meshlink_node **(*full_meshlink_get_all_nodes_by_last_reachable)(struct meshlink_handle *mesh, time_t start, time_t end, struct meshlink_node **nodes, size_t *nmemb) __attribute__((__warn_unused_result__));
struct meshlink_node **(*full_meshlink_get_all_nodes_by_blacklisted)(struct meshlink_handle *mesh, bool blacklisted, struct meshlink_node **nodes, size_t *nmemb) __attribute__((__warn_unused_result__));
dev_class_t (*full_meshlink_get_node_dev_class)(struct meshlink_handle *mesh, struct meshlink_node *node) __attribute__((__warn_unused_result__));
bool (*full_meshlink_get_node_blacklisted)(struct meshlink_handle *mesh, struct meshlink_node *node) __attribute__((__warn_unused_result__));
struct meshlink_submesh *(*full_meshlink_get_node_submesh)(struct meshlink_handle *mesh, struct meshlink_node *node) __attribute__((__warn_unused_result__));
bool (*full_meshlink_get_node_reachability)(struct meshlink_handle *mesh, struct meshlink_node *node, time_t *last_reachable, time_t *last_unreachable);
bool (*full_meshlink_verify)(struct meshlink_handle *mesh, struct meshlink_node *source, const void *data, size_t len, const void *signature, size_t siglen) __attribute__((__warn_unused_result__));
bool (*full_meshlink_set_canonical_address)(struct meshlink_handle *mesh, struct meshlink_node *node, const char *address, const char *port) __attribute__((__warn_unused_result__));
bool (*full_meshlink_clear_canonical_address)(struct meshlink_handle *mesh, struct meshlink_node *node) __attribute__((__warn_unused_result__));
bool (*full_meshlink_add_invitation_address)(struct meshlink_handle *mesh, const char *address, const char *port) __attribute__((__warn_unused_result__));
void (*full_meshlink_clear_invitation_addresses)(struct meshlink_handle *mesh);
char *(*full_meshlink_get_external_address)(struct meshlink_handle *mesh) __attribute__((__warn_unused_result__));
char *(*full_meshlink_get_external_address_for_family)(struct meshlink_handle *mesh, int address_family) __attribute__((__warn_unused_result__));
char *(*full_meshlink_get_local_address_for_family)(struct meshlink_handle *mesh, int address_family) __attribute__((__warn_unused_result__));
bool (*full_meshlink_add_external_address)(struct meshlink_handle *mesh) __attribute__((__warn_unused_result__));
int (*full_meshlink_get_port)(struct meshlink_handle *mesh) __attribute__((__warn_unused_result__));
bool (*full_meshlink_set_port)(struct meshlink_handle *mesh, int port) __attribute__((__warn_unused_result__));
void (*full_meshlink_set_invitation_timeout)(struct meshlink_handle *mesh, int timeout);
char *(*full_meshlink_invite_ex)(struct meshlink_handle *mesh, struct meshlink_submesh *submesh, const char *name, uint32_t flags) __attribute__((__warn_unused_result__));
char *(*full_meshlink_invite)(struct meshlink_handle *mesh, struct meshlink_submesh *submesh, const char *name) __attribute__((__warn_unused_result__));
bool (*full_meshlink_join)(struct meshlink_handle *mesh, const char *invitation) __attribute__((__warn_unused_result__));
char *(*full_meshlink_export)(struct meshlink_handle *mesh) __attribute__((__warn_unused_result__));
bool (*full_meshlink_import)(struct meshlink_handle *mesh, const char *data) __attribute__((__warn_unused_result__));
bool (*full_meshlink_forget_node)(struct meshlink_handle *mesh, struct meshlink_node *node);
bool (*full_meshlink_blacklist)(struct meshlink_handle *mesh, struct meshlink_node *node) __attribute__((__warn_unused_result__));
bool (*full_meshlink_blacklist_by_name)(struct meshlink_handle *mesh, const char *name) __attribute__((__warn_unused_result__));
bool (*full_meshlink_whitelist)(struct meshlink_handle *mesh, struct meshlink_node *node) __attribute__((__warn_unused_result__));
bool (*full_meshlink_whitelist_by_name)(struct meshlink_handle *mesh, const char *name) __attribute__((__warn_unused_result__));
void (*full_meshlink_set_default_blacklist)(struct meshlink_handle *mesh, bool blacklist);
void (*full_meshlink_set_channel_listen_cb)(struct meshlink_handle *mesh, meshlink_channel_listen_cb_t cb);
void (*full_meshlink_set_channel_accept_cb)(struct meshlink_handle *mesh, meshlink_channel_accept_cb_t cb);
void (*full_meshlink_set_channel_receive_cb)(struct meshlink_handle *mesh, struct meshlink_channel *channel, meshlink_channel_receive_cb_t cb);
void (*full_meshlink_set_channel_poll_cb)(struct meshlink_handle *mesh, struct meshlink_channel *channel, meshlink_channel_poll_cb_t cb);
void (*full_meshlink_set_channel_sndbuf)(struct meshlink_handle *mesh, struct meshlink_channel *channel, size_t size);
void (*full_meshlink_set_channel_rcvbuf)(struct meshlink_handle *mesh, struct meshlink_channel *channel, size_t size);
void (*full_meshlink_set_channel_sndbuf_storage)(struct meshlink_handle *mesh, struct meshlink_channel *channel, void *buf, size_t size);
void (*full_meshlink_set_channel_rcvbuf_storage)(struct meshlink_handle *mesh, struct meshlink_channel *channel, void *buf, size_t size);
void (*full_meshlink_set_channel_flags)(struct meshlink_handle *mesh, struct meshlink_channel *channel, uint32_t flags);
struct meshlink_channel *(*full_meshlink_channel_open_ex)(struct meshlink_handle *mesh, struct meshlink_node *node, uint16_t port, meshlink_channel_receive_cb_t cb, const void *data, size_t len, uint32_t flags) __attribute__((__warn_unused_result__));
struct meshlink_channel *(*full_meshlink_channel_open)(struct meshlink_handle *mesh, struct meshlink_node *node, uint16_t port, meshlink_channel_receive_cb_t cb, const void *data, size_t len) __attribute__((__warn_unused_result__));
void (*full_meshlink_channel_shutdown)(struct meshlink_handle *mesh, struct meshlink_channel *channel, int direction);
void (*full_meshlink_channel_close)(struct meshlink_handle *mesh, struct meshlink_channel *channel);
void (*full_meshlink_channel_abort)(struct meshlink_handle *mesh, struct meshlink_channel *channel);
ssize_t (*full_meshlink_channel_send)(struct meshlink_handle *mesh, struct meshlink_channel *channel, const void *data, size_t len) __attribute__((__warn_unused_result__));
bool (*full_meshlink_channel_aio_send)(struct meshlink_handle *mesh, struct meshlink_channel *channel, const void *data, size_t len, meshlink_aio_cb_t cb, void *priv) __attribute__((__warn_unused_result__));
bool (*full_meshlink_channel_aio_fd_send)(struct meshlink_handle *mesh, struct meshlink_channel *channel, int fd, size_t len, meshlink_aio_fd_cb_t cb, void *priv) __attribute__((__warn_unused_result__));
bool (*full_meshlink_channel_aio_receive)(struct meshlink_handle *mesh, struct meshlink_channel *channel, const void *data, size_t len, meshlink_aio_cb_t cb, void *priv) __attribute__((__warn_unused_result__));
bool (*full_meshlink_channel_aio_fd_receive)(struct meshlink_handle *mesh, struct meshlink_channel *channel, int fd, size_t len, meshlink_aio_fd_cb_t cb, void *priv) __attribute__((__warn_unused_result__));
uint32_t (*full_meshlink_channel_get_flags)(struct meshlink_handle *mesh, struct meshlink_channel *channel) __attribute__((__warn_unused_result__));
size_t (*full_meshlink_channel_get_sendq)(struct meshlink_handle *mesh, struct meshlink_channel *channel) __attribute__((__warn_unused_result__));
size_t (*full_meshlink_channel_get_recvq)(struct meshlink_handle *mesh, struct meshlink_channel *channel) __attribute__((__warn_unused_result__));
size_t (*full_meshlink_channel_get_mss)(struct meshlink_handle *mesh, struct meshlink_channel *channel) __attribute__((__warn_unused_result__));
void (*full_meshlink_set_node_channel_timeout)(struct meshlink_handle *mesh, struct meshlink_node *node, int timeout);
void (*full_meshlink_hint_address)(struct meshlink_handle *mesh, struct meshlink_node *node, const struct sockaddr *addr);
void (*full_meshlink_enable_discovery)(struct meshlink_handle *mesh, bool enable);
void (*full_meshlink_hint_network_change)(struct meshlink_handle *mesh);
bool (*full_meshlink_encrypted_key_rotate)(struct meshlink_handle *mesh, const void *key, size_t keylen) __attribute__((__warn_unused_result__));
void (*full_meshlink_set_dev_class_timeouts)(struct meshlink_handle *mesh, dev_class_t devclass, int pinginterval, int pingtimeout);
void (*full_meshlink_set_dev_class_fast_retry_period)(struct meshlink_handle *mesh, dev_class_t devclass, int fast_retry_period);
void (*full_meshlink_set_dev_class_maxtimeout)(struct meshlink_handle *mesh, dev_class_t devclass, int maxtimeout);
void (*full_meshlink_reset_timers)(struct meshlink_handle *mesh);
void (*full_meshlink_set_inviter_commits_first)(struct meshlink_handle *mesh, bool inviter_commits_first);
void (*full_meshlink_set_external_address_discovery_url)(struct meshlink_handle *mesh, const char *url);
void (*full_meshlink_set_scheduling_granularity)(struct meshlink_handle *mesh, long granularity);
void (*full_meshlink_set_storage_policy)(struct meshlink_handle *mesh, meshlink_storage_policy_t policy);

full_devtool_set_inviter_commits_first_t *full_devtool_set_inviter_commits_first;
void (*full_devtool_reset_node_counters)(struct meshlink_handle *mesh, meshlink_node_t *node, struct devtool_node_status *);

void init_full(void) {
	void *handle = dlopen("libmeshlink.so", RTLD_LAZY | RTLD_LOCAL | RTLD_DEEPBIND);
	assert(handle);

	assert(full_meshlink_errno = dlsym(handle, "meshlink_errno"));
	assert(full_meshlink_strerror = dlsym(handle, "meshlink_strerror"));
	assert(full_meshlink_open_params_init = dlsym(handle, "meshlink_open_params_init"));
	assert(full_meshlink_open_params_free = dlsym(handle, "meshlink_open_params_free"));
	assert(full_meshlink_open_params_set_netns = dlsym(handle, "meshlink_open_params_set_netns"));
	assert(full_meshlink_open_params_set_storage_key = dlsym(handle, "meshlink_open_params_set_storage_key"));
	assert(full_meshlink_open_params_set_storage_policy = dlsym(handle, "meshlink_open_params_set_storage_policy"));
	assert(full_meshlink_open_params_set_lock_filename = dlsym(handle, "meshlink_open_params_set_lock_filename"));
	assert(full_meshlink_open_ex = dlsym(handle, "meshlink_open_ex"));
	assert(full_meshlink_open = dlsym(handle, "meshlink_open"));
	assert(full_meshlink_open_encrypted = dlsym(handle, "meshlink_open_encrypted"));
	assert(full_meshlink_open_ephemeral = dlsym(handle, "meshlink_open_ephemeral"));
	assert(full_meshlink_submesh_open = dlsym(handle, "meshlink_submesh_open"));
	assert(full_meshlink_start = dlsym(handle, "meshlink_start"));
	assert(full_meshlink_stop = dlsym(handle, "meshlink_stop"));
	assert(full_meshlink_close = dlsym(handle, "meshlink_close"));
	assert(full_meshlink_destroy = dlsym(handle, "meshlink_destroy"));
	assert(full_meshlink_destroy_ex = dlsym(handle, "meshlink_destroy_ex"));
	assert(full_meshlink_set_receive_cb = dlsym(handle, "meshlink_set_receive_cb"));
	assert(full_meshlink_set_connection_try_cb = dlsym(handle, "meshlink_set_connection_try_cb"));
	assert(full_meshlink_set_node_status_cb = dlsym(handle, "meshlink_set_node_status_cb"));
	assert(full_meshlink_set_node_pmtu_cb = dlsym(handle, "meshlink_set_node_pmtu_cb"));
	assert(full_meshlink_set_node_duplicate_cb = dlsym(handle, "meshlink_set_node_duplicate_cb"));
	assert(full_meshlink_set_log_cb = dlsym(handle, "meshlink_set_log_cb"));
	assert(full_meshlink_set_error_cb = dlsym(handle, "meshlink_set_error_cb"));
	assert(full_meshlink_set_blacklisted_cb = dlsym(handle, "meshlink_set_blacklisted_cb"));
	assert(full_meshlink_send = dlsym(handle, "meshlink_send"));
	assert(full_meshlink_get_pmtu = dlsym(handle, "meshlink_get_pmtu"));
	assert(full_meshlink_get_self = dlsym(handle, "meshlink_get_self"));
	assert(full_meshlink_get_node = dlsym(handle, "meshlink_get_node"));
	assert(full_meshlink_get_submesh = dlsym(handle, "meshlink_get_submesh"));
	assert(full_meshlink_get_fingerprint = dlsym(handle, "meshlink_get_fingerprint"));
	assert(full_meshlink_get_all_nodes = dlsym(handle, "meshlink_get_all_nodes"));
	assert(full_meshlink_sign = dlsym(handle, "meshlink_sign"));
	assert(full_meshlink_get_all_nodes_by_dev_class = dlsym(handle, "meshlink_get_all_nodes_by_dev_class"));
	assert(full_meshlink_get_all_nodes_by_submesh = dlsym(handle, "meshlink_get_all_nodes_by_submesh"));
	assert(full_meshlink_get_all_nodes_by_last_reachable = dlsym(handle, "meshlink_get_all_nodes_by_last_reachable"));
	assert(full_meshlink_get_all_nodes_by_blacklisted = dlsym(handle, "meshlink_get_all_nodes_by_blacklisted"));
	assert(full_meshlink_get_node_dev_class = dlsym(handle, "meshlink_get_node_dev_class"));
	assert(full_meshlink_get_node_blacklisted = dlsym(handle, "meshlink_get_node_blacklisted"));
	assert(full_meshlink_get_node_submesh = dlsym(handle, "meshlink_get_node_submesh"));
	assert(full_meshlink_get_node_reachability = dlsym(handle, "meshlink_get_node_reachability"));
	assert(full_meshlink_verify = dlsym(handle, "meshlink_verify"));
	assert(full_meshlink_set_canonical_address = dlsym(handle, "meshlink_set_canonical_address"));
	assert(full_meshlink_clear_canonical_address = dlsym(handle, "meshlink_clear_canonical_address"));
	assert(full_meshlink_add_invitation_address = dlsym(handle, "meshlink_add_invitation_address"));
	assert(full_meshlink_clear_invitation_addresses = dlsym(handle, "meshlink_clear_invitation_addresses"));
	assert(full_meshlink_get_external_address = dlsym(handle, "meshlink_get_external_address"));
	assert(full_meshlink_get_external_address_for_family = dlsym(handle, "meshlink_get_external_address_for_family"));
	assert(full_meshlink_get_local_address_for_family = dlsym(handle, "meshlink_get_local_address_for_family"));
	assert(full_meshlink_add_external_address = dlsym(handle, "meshlink_add_external_address"));
	assert(full_meshlink_get_port = dlsym(handle, "meshlink_get_port"));
	assert(full_meshlink_set_port = dlsym(handle, "meshlink_set_port"));
	assert(full_meshlink_set_invitation_timeout = dlsym(handle, "meshlink_set_invitation_timeout"));
	assert(full_meshlink_invite_ex = dlsym(handle, "meshlink_invite_ex"));
	assert(full_meshlink_invite = dlsym(handle, "meshlink_invite"));
	assert(full_meshlink_join = dlsym(handle, "meshlink_join"));
	assert(full_meshlink_export = dlsym(handle, "meshlink_export"));
	assert(full_meshlink_import = dlsym(handle, "meshlink_import"));
	assert(full_meshlink_forget_node = dlsym(handle, "meshlink_forget_node"));
	assert(full_meshlink_blacklist = dlsym(handle, "meshlink_blacklist"));
	assert(full_meshlink_blacklist_by_name = dlsym(handle, "meshlink_blacklist_by_name"));
	assert(full_meshlink_whitelist = dlsym(handle, "meshlink_whitelist"));
	assert(full_meshlink_whitelist_by_name = dlsym(handle, "meshlink_whitelist_by_name"));
	assert(full_meshlink_set_default_blacklist = dlsym(handle, "meshlink_set_default_blacklist"));
	assert(full_meshlink_set_channel_listen_cb = dlsym(handle, "meshlink_set_channel_listen_cb"));
	assert(full_meshlink_set_channel_accept_cb = dlsym(handle, "meshlink_set_channel_accept_cb"));
	assert(full_meshlink_set_channel_receive_cb = dlsym(handle, "meshlink_set_channel_receive_cb"));
	assert(full_meshlink_set_channel_poll_cb = dlsym(handle, "meshlink_set_channel_poll_cb"));
	assert(full_meshlink_set_channel_sndbuf = dlsym(handle, "meshlink_set_channel_sndbuf"));
	assert(full_meshlink_set_channel_rcvbuf = dlsym(handle, "meshlink_set_channel_rcvbuf"));
	assert(full_meshlink_set_channel_sndbuf_storage = dlsym(handle, "meshlink_set_channel_sndbuf_storage"));
	assert(full_meshlink_set_channel_rcvbuf_storage = dlsym(handle, "meshlink_set_channel_rcvbuf_storage"));
	assert(full_meshlink_set_channel_flags = dlsym(handle, "meshlink_set_channel_flags"));
	assert(full_meshlink_channel_open_ex = dlsym(handle, "meshlink_channel_open_ex"));
	assert(full_meshlink_channel_open = dlsym(handle, "meshlink_channel_open"));
	assert(full_meshlink_channel_shutdown = dlsym(handle, "meshlink_channel_shutdown"));
	assert(full_meshlink_channel_close = dlsym(handle, "meshlink_channel_close"));
	assert(full_meshlink_channel_abort = dlsym(handle, "meshlink_channel_abort"));
	assert(full_meshlink_channel_send = dlsym(handle, "meshlink_channel_send"));
	assert(full_meshlink_channel_aio_send = dlsym(handle, "meshlink_channel_aio_send"));
	assert(full_meshlink_channel_aio_fd_send = dlsym(handle, "meshlink_channel_aio_fd_send"));
	assert(full_meshlink_channel_aio_receive = dlsym(handle, "meshlink_channel_aio_receive"));
	assert(full_meshlink_channel_aio_fd_receive = dlsym(handle, "meshlink_channel_aio_fd_receive"));
	assert(full_meshlink_channel_get_flags = dlsym(handle, "meshlink_channel_get_flags"));
	assert(full_meshlink_channel_get_sendq = dlsym(handle, "meshlink_channel_get_sendq"));
	assert(full_meshlink_channel_get_recvq = dlsym(handle, "meshlink_channel_get_recvq"));
	assert(full_meshlink_channel_get_mss = dlsym(handle, "meshlink_channel_get_mss"));
	assert(full_meshlink_set_node_channel_timeout = dlsym(handle, "meshlink_set_node_channel_timeout"));
	assert(full_meshlink_hint_address = dlsym(handle, "meshlink_hint_address"));
	assert(full_meshlink_enable_discovery = dlsym(handle, "meshlink_enable_discovery"));
	assert(full_meshlink_hint_network_change = dlsym(handle, "meshlink_hint_network_change"));
	assert(full_meshlink_encrypted_key_rotate = dlsym(handle, "meshlink_encrypted_key_rotate"));
	assert(full_meshlink_set_dev_class_timeouts = dlsym(handle, "meshlink_set_dev_class_timeouts"));
	assert(full_meshlink_set_dev_class_fast_retry_period = dlsym(handle, "meshlink_set_dev_class_fast_retry_period"));
	assert(full_meshlink_set_dev_class_maxtimeout = dlsym(handle, "meshlink_set_dev_class_maxtimeout"));
	assert(full_meshlink_reset_timers = dlsym(handle, "meshlink_reset_timers"));
	assert(full_meshlink_set_inviter_commits_first = dlsym(handle, "meshlink_set_inviter_commits_first"));
	assert(full_meshlink_set_external_address_discovery_url = dlsym(handle, "meshlink_set_external_address_discovery_url"));
	assert(full_meshlink_set_scheduling_granularity = dlsym(handle, "meshlink_set_scheduling_granularity"));
	assert(full_meshlink_set_storage_policy = dlsym(handle, "meshlink_set_storage_policy"));

	assert(full_devtool_set_inviter_commits_first = dlsym(handle, "devtool_set_inviter_commits_first"));
	assert(full_devtool_reset_node_counters = dlsym(handle, "devtool_reset_node_counters"));
}
